### PR TITLE
Update DeviceInfoSettings.java

### PR DESCRIPTION
**Pull request by NachiketNamjoshi**
Fix derp

### CODE REVIEW

**Comment by crdnl2** [comment]
Done! It doesn't work!

**Comment by Adarsh-MR** [comment]
That was too much rude xD

**Comment by rohitporoli** [comment]
Lmao! 😆

**Comment by crdnl2** [comment]
@NachiketNamjoshi 😉 

@Adarsh-MR 😝 Lmao 😆

**Pull request closed without merging**
